
get_config = arti_slot_control_mcm.get_config
print_dbg = arti_slot_control_mcm.print_dbg
ini_conf = ini_file("items\\settings\\plate_config.ltx")


function add_recipes()
    workshop_autoinject.add_override_recipe("x_af_frames_up", "3, recipe_expert_0, af_frames,1,af_night_star,1", 3)
    workshop_autoinject.add_override_recipe("x_af_grid_up", "3, recipe_expert_0, af_grid,1,af_gravi,1", 3)
    workshop_autoinject.add_override_recipe("x_af_cooler_up", "3, recipe_expert_1, af_cooler,1,af_fuzz_kolobok,1", 3)
    workshop_autoinject.add_override_recipe("x_af_freon_up", "3, recipe_expert_1, af_freon,1,af_baloon,1", 3)
    workshop_autoinject.add_override_recipe("x_af_camelbak_up", "3, recipe_expert_2, af_camelbak,1,af_dummy_battery,1", 3)
    workshop_autoinject.add_override_recipe("x_af_surge_up", "3, recipe_expert_3, af_surge, 1 ,af_electra_sparkler,1", 3)
end





OnItemSelect = item_repair.UIRepair.OnItemSelect
function item_repair.UIRepair:OnItemSelect(n)
    local obj_1 = self.CC[1]:GetCell_Selected(true)
    if obj_1 and SYS_GetParam(0, obj_1:section(), "material") then
        self.add_condition = 0
    end
    OnItemSelect(self, n)
end

CanRepair = inventory_upgrades.can_repair_item

function on_game_start()
    workshop_autoinject.add_override_recipe("af_cooler", "3, recipe_advanced_2, e_syringe,2,detector_geiger,1,af_camelbak,1,prt_i_plastic,3", 2)
    workshop_autoinject.add_override_recipe("af_freon", "3, recipe_advanced_1, detector_advanced,1,af_iam,1,prt_i_scrap,5,prt_i_fasteners,4", 2)
    workshop_autoinject.add_override_recipe("af_frames_up", "3, recipe_expert_0, af_frames,1,af_night_star,1", 2)
    workshop_autoinject.add_override_recipe("af_grid_up", "3, recipe_expert_0, af_grid,1,af_gravi,1", 2)
    workshop_autoinject.add_override_recipe("af_cooler_up", "3, recipe_expert_1, af_cooler,1,af_fuzz_kolobok,1", 2)
    workshop_autoinject.add_override_recipe("af_freon_up", "3, recipe_expert_1, af_freon,1,af_cristall,1", 2)
    workshop_autoinject.add_override_recipe("af_camelbak_up", "3, recipe_expert_2, af_camelbak,1,af_dummy_battery,1", 2)
    workshop_autoinject.add_override_recipe("af_surge_up", "3, recipe_expert_3, af_surge,1 ,af_electra_sparkler,1", 2)
end